FROM golang:1.14.3-alpine as builder

WORKDIR /client

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd/client .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o client .


######## Start a new stage from scratch #######
FROM alpine:3.11.6  

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /client/client .

CMD ["./client"] 