version: '3.3'

networks:
  basic:

services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    expose:
      - '3000'
    networks:
      - basic

  user1:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - basic

  user2:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - basic

  user3:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - basic